

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lineare_unabhängigkeit;

import java.util.Vector;
import java.util.Arrays;
/**
 *
 * @author xi97giq
 */
public class Lineare_unabhängigkeit_form extends javax.swing.JFrame {

    /**
     * Creates new form Lineare_unabhängigkeit_form
     */
    public Lineare_unabhängigkeit_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("                 ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("                 ");

        jTextField3.setText("                 ");

        jTextField4.setText("                 ");

        jTextField5.setText("                 ");

        jTextField6.setText("                 ");

        jTextField7.setText("                 ");

        jTextField8.setText("                 ");

        jTextField9.setText("                 ");

        jTextField10.setText("                 ");

        jTextField11.setText("                 ");

        jTextField12.setText("                 ");

        jTextField13.setText("                 ");

        jTextField14.setText("                 ");

        jTextField15.setText("                 ");

        jTextField16.setText("                 ");

        jTextField17.setText("                 ");

        jTextField18.setText("                 ");

        jTextField19.setText("                 ");

        jTextField20.setText("                 ");

        jTextField21.setText("                 ");

        jTextField22.setText("                 ");

        jTextField23.setText("                 ");

        jTextField24.setText("                 ");

        jTextField25.setText("                 ");

        jTextField26.setText("                 ");

        jTextField27.setText("                 ");

        jTextField28.setText("                 ");

        jTextField29.setText("                 ");

        jTextField30.setText("                 ");

        jTextField31.setText("                 ");

        jTextField32.setText("                 ");

        jTextField33.setText("                 ");

        jTextField34.setText("                 ");
        jTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField34ActionPerformed(evt);
            }
        });

        jTextField35.setText("                 ");
        jTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField35ActionPerformed(evt);
            }
        });

        jTextField36.setText("                 ");

        jTextField37.setText("                 ");

        jTextField38.setText("                 ");

        jTextField39.setText("                 ");

        jTextField40.setText("                 ");
        jTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField40ActionPerformed(evt);
            }
        });

        jTextField41.setText("                 ");

        jTextField42.setText("                 ");

        jTextField43.setText("                 ");

        jTextField44.setText("                 ");

        jTextField45.setText("                 ");

        jTextField46.setText("                 ");

        jTextField47.setText("                 ");

        jTextField48.setText("                 ");

        jTextField49.setText("                 ");

        jTextField50.setText("                 ");

        jTextField51.setText("                 ");

        jTextField52.setText("                 ");

        jTextField53.setText("                 ");

        jTextField54.setText("                 ");

        jTextField55.setText("                 ");

        jTextField56.setText("                 ");

        jTextField57.setText("                 ");

        jTextField58.setText("                 ");

        jTextField59.setText("                 ");

        jTextField60.setText("                 ");

        jTextField61.setText("                 ");

        jTextField62.setText("                 ");

        jTextField63.setText("                 ");

        jLabel1.setText("Vektor1");

        jLabel2.setText("Vektor 2");

        jLabel3.setText("Vektor 3");

        jLabel4.setText("Vektor 4");

        jLabel5.setText("Vektor 5");

        jLabel6.setText("Vektor 6");

        jLabel7.setText("Vektor 7");

        jLabel8.setText("Auf lineare Unabhängigkeit prüfen");

        jButton1.setText("Prüfen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel7)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Vector<Double> vec1=new Vector<>(10);
        Vector<Double> vec2=new Vector<>(10);
         Vector<Double> vec3=new Vector<>(10);
        Vector<Double> vec4=new Vector<>(10);
         Vector<Double> vec5=new Vector<>(10);
        Vector<Double> vec6=new Vector<>(10);
         Vector<Double> vec7=new Vector<>(10);
        if(this.jTextField1.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField1.getText()));
        }
        if(this.jTextField2.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField2.getText()));
        }
        if(this.jTextField3.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField3.getText()));
        }
        if(this.jTextField4.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField4.getText()));
        }
        if(this.jTextField5.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField5.getText()));
        }
        if(this.jTextField6.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField6.getText()));
        }
        if(this.jTextField7.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField7.getText()));
        }
        if(this.jTextField8.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField8.getText()));
        }
        if(this.jTextField9.getText().equals("                 ")) {
        } else {
            vec1.add(Double.parseDouble(this.jTextField9.getText()));
        }
        
        
        
        if(this.jTextField10.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField10.getText()));
        }
        if(this.jTextField11.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField11.getText()));
        }
        if(this.jTextField12.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField12.getText()));
        }
        if(this.jTextField13.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField13.getText()));
        }
        if(this.jTextField14.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField14.getText()));
        }
        if(this.jTextField15.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField15.getText()));
        }
        if(this.jTextField16.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField16.getText()));
        }
        if(this.jTextField17.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField17.getText()));
        }
        if(this.jTextField18.getText().equals("                 ")) {
        } else {
            vec2.add(Double.parseDouble(this.jTextField18.getText()));
        }
        
        
        
        
        
        
        
        if(this.jTextField19.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField19.getText()));
        }
        if(this.jTextField20.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField20.getText()));
        }
        if(this.jTextField21.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField21.getText()));
        }
        if(this.jTextField22.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField22.getText()));
        }
        if(this.jTextField23.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField23.getText()));
        }
        if(this.jTextField24.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField24.getText()));
        }
        if(this.jTextField25.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField25.getText()));
        }
        if(this.jTextField26.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField26.getText()));
        }
        if(this.jTextField27.getText().equals("                 ")) {
        } else {
            vec3.add(Double.parseDouble(this.jTextField27.getText()));
        }
        
        
        
        
        
        
        
        
        
        
        
        
        if(this.jTextField28.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField28.getText()));
        }
        if(this.jTextField32.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField32.getText()));
        }
        if(this.jTextField33.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField33.getText()));
        }
        if(this.jTextField34.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField34.getText()));
        }
        if(this.jTextField35.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField35.getText()));
        }
        if(this.jTextField36.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField36.getText()));
        }
        if(this.jTextField37.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField37.getText()));
        }
        if(this.jTextField38.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField38.getText()));
        }
        if(this.jTextField39.getText().equals("                 ")) {
        } else {
            vec4.add(Double.parseDouble(this.jTextField39.getText()));
        }
        
        
        
        
        
        
        
        
        
        
        
        
        if(this.jTextField29.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField29.getText()));
        }
        if(this.jTextField40.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField40.getText()));
        }
        if(this.jTextField41.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField41.getText()));
        }
        if(this.jTextField42.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField42.getText()));
        }
        if(this.jTextField43.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField43.getText()));
        }
        if(this.jTextField44.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField44.getText()));
        }
        if(this.jTextField45.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField45.getText()));
        }
        if(this.jTextField46.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField46.getText()));
        }
        if(this.jTextField47.getText().equals("                 ")) {
        } else {
            vec5.add(Double.parseDouble(this.jTextField47.getText()));
        }
        
        
        
        
        
        
        
        
        
        
        if(this.jTextField30.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField30.getText()));
        }
        if(this.jTextField48.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField48.getText()));
        }
        if(this.jTextField49.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField49.getText()));
        }
        if(this.jTextField50.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField50.getText()));
        }
        if(this.jTextField51.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField51.getText()));
        }
        if(this.jTextField52.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField52.getText()));
        }
        if(this.jTextField53.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField53.getText()));
        }
        if(this.jTextField54.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField54.getText()));
        }
        if(this.jTextField55.getText().equals("                 ")) {
        } else {
            vec6.add(Double.parseDouble(this.jTextField55.getText()));
        }
        
        
       
        
        
        
        
        
        
        if(this.jTextField31.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField31.getText()));
        }
        if(this.jTextField56.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField56.getText()));
        }
        if(this.jTextField57.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField57.getText()));
        }
        if(this.jTextField58.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField58.getText()));
        }
        if(this.jTextField59.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField59.getText()));
        }
        if(this.jTextField60.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField60.getText()));
        }
        if(this.jTextField61.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField61.getText()));
        }
        if(this.jTextField62.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField62.getText()));
        }
        if(this.jTextField63.getText().equals("                 ")) {
        } else {
            vec7.add(Double.parseDouble(this.jTextField63.getText()));
        }
        
        vec1.trimToSize();vec2.trimToSize();vec3.trimToSize();vec4.trimToSize();
        vec5.trimToSize();vec6.trimToSize();vec7.trimToSize();
        
        String ausgabe="";

        Vector<Vector<Double>> vec0=new Vector<>(7);
        
        
            vec0.add(vec1);
            vec0.add(vec2);
            vec0.add(vec3);
            vec0.add(vec4);
            vec0.add(vec5);
            vec0.add(vec6);
            vec0.add(vec7);
            
            int j=7;
       for(int i =0;i<j;i++){
           if(vec0.elementAt(i).isEmpty()){vec0.remove(i);j--;i--;}
       }
       vec0.trimToSize();
        
       
       int sizex=vec0.elementAt(0).size();
       boolean samelength=true;
        for(int i=1;i<vec0.size();i++){
            if(vec0.elementAt(i).size()!=sizex)samelength=false;
        }
       
        if(samelength){
            boolean lin= isLIN(zeilenstufenform(vectorHorizontal(vec0)));
            
            if(lin==true)ausgabe="Die Vektoren sind linear unabhängig";
            else ausgabe="Die Vektoren sind linear abhänging";
            
            
            
        }
        else {ausgabe="!!Vectors dont have same dimension!!";}
        
        
        
        this.jLabel9.setText(ausgabe);
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField35ActionPerformed

    private void jTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField34ActionPerformed

    private void jTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField40ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lineare_unabhängigkeit_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lineare_unabhängigkeit_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lineare_unabhängigkeit_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lineare_unabhängigkeit_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lineare_unabhängigkeit_form().setVisible(true);
            }
        });
    }
    
    
    
    //Input is the vertical-column Vector of all columns. The programm assumes, that there are no empty columns.
    //And it is also assuming, that all vectors have the same length.
    //Outuput are n vectors in a vector with n=the size of the first vertical vector in the input vec.
    
    
    public static Vector<Vector<Double>> vectorHorizontal(Vector<Vector<Double>> vec){
        
        Vector<Vector<Double>> vecArray = new Vector<>(9);
        
        
        Vector<Double> vec1 = new Vector<>(vec.size());
        Vector<Double> vec2 = new Vector<>(vec.size());
        Vector<Double> vec3 = new Vector<>(vec.size());
        Vector<Double> vec4 = new Vector<>(vec.size());
        Vector<Double> vec5 = new Vector<>(vec.size());
        Vector<Double> vec6 = new Vector<>(vec.size());
        Vector<Double> vec7 = new Vector<>(vec.size());
        Vector<Double> vec8 = new Vector<>(vec.size());
        Vector<Double> vec9 = new Vector<>(vec.size());
        
        
        int lengthOfVec = vec.elementAt(0).size();
         if (lengthOfVec>0){for(int i=0;i<vec.size();i++){vec1.add(vec.elementAt(i).elementAt(0));}}
        if (lengthOfVec>1){for(int i=0;i<vec.size();i++){vec2.add(vec.elementAt(i).elementAt(1));}}
        if (lengthOfVec>2){for(int i=0;i<vec.size();i++){vec3.add(vec.elementAt(i).elementAt(2));}}
        if (lengthOfVec>3){for(int i=0;i<vec.size();i++){vec4.add(vec.elementAt(i).elementAt(3));}}
        if (lengthOfVec>4){for(int i=0;i<vec.size();i++){vec5.add(vec.elementAt(i).elementAt(4));}}
        if (lengthOfVec>5){for(int i=0;i<vec.size();i++){vec6.add(vec.elementAt(i).elementAt(5));}}
        if (lengthOfVec>6){for(int i=0;i<vec.size();i++){vec7.add(vec.elementAt(i).elementAt(6));}}
        if (lengthOfVec>7){for(int i=0;i<vec.size();i++){vec8.add(vec.elementAt(i).elementAt(7));}}
        if (lengthOfVec>8){for(int i=0;i<vec.size();i++){vec9.add(vec.elementAt(i).elementAt(8));}}
        
        if(!vec1.isEmpty())vecArray.add(vec1);
        if(!vec2.isEmpty())vecArray.add(vec2);
        if(!vec3.isEmpty())vecArray.add(vec3);
        if(!vec4.isEmpty())vecArray.add(vec4);
        if(!vec5.isEmpty())vecArray.add(vec5);
        if(!vec6.isEmpty())vecArray.add(vec6);
        if(!vec7.isEmpty())vecArray.add(vec7);
        if(!vec8.isEmpty())vecArray.add(vec8);
        if(!vec9.isEmpty())vecArray.add(vec9);
        
        vecArray.trimToSize();
        
        
        
        

        
        
        
        
        
        
        return vecArray;
    }
    
    
    public static Vector<Vector<Double>> swapLines(Vector<Vector<Double>> vec){
        int m =vec.size();
        int n =vec.elementAt(0).size();
        
        for(int s=0;s<n;s++){
        
        for(int j=0;j<m;j++){
        int indexc=j;
        for(int i=j;i<n;i++){
            if (vec.elementAt(i).elementAt(s)!=0)vec=swap(vec,i,indexc);
            indexc++;
        }}}
        
        return vec;
    }
    
    public static Vector<Vector<Double>> swap(Vector<Vector<Double>> vec, int a,int b){
        Vector<Double> alpha=vec.elementAt(a);
        Vector<Double> beta=vec.elementAt(b);
        
        vec.set(a, beta);
        vec.set(b,alpha);
        
        return vec;
    }
   
    
    public static MatrixPivots zeilenstufenform(Vector<Vector<Double>> vec){
        vec =swapLines(vec);
        int[]pivots =new int[vec.size()];
        
        for(int i=0;i<vec.size();i++){
            pivots[i]=pivotNumberOfVec(vec.elementAt(i));
        }
        if(!isZSF(pivots)){
          for(int j=0;j<vec.size();j++){
              System.out.println(pivots[j]);
              System.out.println(vec.size());
              System.out.println();
              System.out.println(vec.elementAt(0).elementAt(0));
              System.out.println(vec.elementAt(0).elementAt(1));
              System.out.println(vec.elementAt(1).elementAt(0));
              System.out.println(vec.elementAt(1).elementAt(1));
              System.out.println();
              System.out.println();
              System.out.println(vec.elementAt(0).size());
              System.out.println(vec.elementAt(1).size());
              System.out.println();
              System.out.println();
              System.out.println();
                      
              double factorA = vec.elementAt(j).elementAt(pivots[j]);
              for(int i=j+1;i<vec.size();i++){
              double factorB =vec.elementAt(i).elementAt(pivots[j]);
                     for(int h=0;h<vec.elementAt(i).size();h++){
                     double newValue=(vec.elementAt(i).elementAt(h))-vec.elementAt(j).elementAt(h)*(factorB/factorA);
                     vec.elementAt(i).set(h, newValue);
                     }
              
              }
              
              for(int i=0;i<vec.size();i++){
            pivots[i]=pivotNumberOfVec(vec.elementAt(i));
        }
              
          }  
        }
        
        for(int i=0;i<vec.size();i++){
            pivots[i]=pivotNumberOfVec(vec.elementAt(i));
        }
        MatrixPivots x= new MatrixPivots(vec,pivots);
        return x;
    }
    
    public static boolean isLIN(MatrixPivots x){
        int[] pivots= x.pivots;
        int[] pivots2= pivots.clone();
        Vector<Vector<Double>> matrix = x.matrix;
        
        int length=matrix.elementAt(0).size();
        
        double[]solution= new double[length];
        
        for(int i=0;i<length;i++){
            boolean pivotsContain = false;
            for(int j=0;j<pivots.length;j++)
           {if(pivots[j]==i) pivotsContain=true;}
            if(!pivotsContain)solution[i]=0;
       
        }
        for(int p=matrix.size()-1;p>=0;p--){
            
        
        for(int i=length-1;i>=0&&i>=pivots[p];i--){  
            
            
            
     
            boolean pivotsContain = false;
            for(int j=0;j<pivots2.length;j++)
           {if(pivots2[j]==i) pivotsContain=true;}
            if(pivotsContain){
                double sum=0;
                for(int h=i+1;h<length-1;h++){
                    sum+=(solution[h])*(matrix.elementAt(p).elementAt(h));
                }
                
                solution[i]=(0-sum)/matrix.elementAt(p).elementAt(i);
                for(int j=0;j<pivots2.length;j++){if(pivots2[j]==i){
                    int[]newPivots= new int[pivots2.length-1];
                    for(int y=0;y<newPivots.length;y++){
                        newPivots[y]=y<j?pivots2[y]:pivots2[y+1];
                     
                    }
                    pivots2=newPivots;
                
                }
                    
                
                
                }
        }}}
        
        boolean checkSolution=true;
        
        for (int i=0;i<solution.length;i++){
            if(solution[i]!=0)checkSolution=false;
        }
        
        return checkSolution;
        
        }
        
        
   
    
    public static boolean isZSF(int[]pivots){
        boolean ret=true;
        int start=pivots[0];
        for(int i=1;i<pivots.length;i++){
            if(pivots[i]>=start)ret=false;
            start=pivots[i];
        }
        return ret;
    }
    
    
    public static int pivotNumberOfVec(Vector<Double> vec){
        int ret=0;
        for(int i=0;i<vec.size();i++)if(vec.elementAt(i)==0&&i<vec.size()-1)ret=ret+1;
        return ret;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}

 class MatrixPivots{
        Vector<Vector<Double>> matrix;
        int[] pivots;
         MatrixPivots(Vector<Vector<Double>> matrix1,int[]pivots1){
            matrix=matrix1;
            pivots=pivots1;
        }
    }